"""
O que o módulo faz
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaasssssssssssssssssssssssssssssssssssssssssssss
s
s
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

"""
