from pathlib import Path 

ROOT_FOLDER = Path(__file__).parent
FILES_FOLDER = ROOT_FOLDER / 'file'
WINDOW_ICON_PATH = FILES_FOLDER / 'icon.png'

#sizing 
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24 
SMALL_FONT_SIZE = 18 
TEXT_MARGIN = 15
MINIMUM_WIDTH = 650

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'